### ISSUE TITLE
tries to apply ipv4 rule to ipv6 address 

### ISSUE THREAD

**Issue by 54696d21** [muzuiget/mitmpcap#1]
Thank you very much for this addon :)
On my connection (dual stack ipv4/ipv6) it occasionally throws the following error.
```
Addon error: Traceback (most recent call last):
  File "mitmpcap.py", line 118, in response
    self.export_request(client_addr, server_addr, flow.request)
  File "mitmpcap.py", line 129, in export_request
    self.exporter.packets(*client_addr, *server_addr, payload)
  File "mitmpcap.py", line 59, in packets
    self.packet(src_host, src_port,
  File "mitmpcap.py", line 39, in packet
    ipv4_args.extend(map(int, dst_host.split('.')))
ValueError: invalid literal for int() with base 10: '2a02:26f0:12d::58dd:d62b'
```

**Comment by muzuiget** [comment]
Currently IPv6 not yet support.

**Comment by christian-bromann** [comment]
@muzuiget what would you suggest as solution? Happy to contribute.

**Comment by muzuiget** [comment]
#10
